### ISSUE TITLE
slurm_su_bank_python3 based upon slurm-bank

### ISSUE THREAD

**Issue by ds-04** [barrymoo/slurm-bank#1]
Hi Barry,

(not a real issue)

Just wanted to let you know I've been working on this project:

https://github.com/ds-04/slurm_su_bank_python3

I have attributed credit to you in the readme and maintained the MIT license file.

thanks
David

**Comment by chiroptical** [comment]
Super happy that is was useful to you :snail: :rocket:

I haven't touched this code in like 1.5 years but if you have any question please let me know. AFAIK people are still using it at Pitt CRC

**Comment by chiroptical** [comment]
Ahh, I haven't touched this one in much longer. Anyway, I'll close for now but feel free to ask questions.
